/// Flutter icons AppLogo
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppLogo
///      fonts:
///       - asset: fonts/AppLogo.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class AppLogoInfo {
  AppLogoInfo._();

  static const _kFontFam = 'AppLogo';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData foreground_logo = IconData(
    0xe800,
    fontFamily: _kFontFam,
    // ignore: avoid_redundant_argument_values
    fontPackage: _kFontPkg,
  );
}
